### ISSUE TITLE
Audio messup

### ISSUE THREAD

**Issue by bluwattl** [bluwattl/IntoTheWilds#2]
I have looked on the sheet about audio and it's not working. Could someone tell me what is wrong?

**Comment by notklaatu** [comment]
This is AMAZING!!!!!

The audio seems to be working for me. I'm on Linux. I'll try the game on a Mac and Windows when I get a chance. 

What exactly is not working for you? Are you not hearing the audio at all, or is it not switching to battle music at the appropriate time?

**Comment by bluwattl** [comment]
? I thought I closed that issue? Anyway, it works for me. Thanks
