### ISSUE TITLE
Add .DS_Store to .gitignore

### ISSUE THREAD

**Issue by notklaatu** [bluwattl/IntoTheWilds#3]
You don't need to track the .DS_Store file. It's meta data that Macs generate because of reasons[?].

Add it to your .gitignore file. You can do that from a terminal, as long as you are in your IntoTheWilds directory. To get to your IntoTheWilds directory, type ``cd`` into the terminal, and then drag IntoTheWilds into the terminal. It will paste the file path into the terminal for you.

Once you're there, do this:

    $ echo .DS_Store >> .gitignore

This is non-urgent.

**Comment by bluwattl** [comment]
Do I add the `$` or is that the start of the command line?

**Comment by notklaatu** [comment]
Yeah that's just the start of the command line (the "prompt"). So don't type that.

On 16 October 2017 4:15:11 PM NZDT, bluwattl <notifications@github.com> wrote:
>Do I add the `$` or is that the start of the command line?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bluwattl/IntoTheWilds/issues/3#issuecomment-336769897

-- 
Klaatu

**Comment by bluwattl** [comment]
I did that, it just went to a new prompt, is that what's supposed to happen?

**Comment by notklaatu** [comment]
Yep, that's pretty much as exciting as it gets.

To verify your work, from that same prompt, you can do:

    $ cat .gitignore

And that will dump the contents of .gitignore into the terminal. It should contain, at the very least, ``.DS_Store``

(Mind you, you have to be in the same place, so if you've closed the terminal, open it back up, type ``cd`` and then drag your git folder to the terminal to paste it, and then type ``cat .gitignore``)

**Comment by bluwattl** [comment]
Yep.
