### ISSUE TITLE
Confusing Combat

### ISSUE THREAD

**Issue by cyanidecupcake** [bluwattl/IntoTheWilds#7]
The controls aren't clear for how to enter and then participate in combat.  

I have tried using the W, A, S, D keys (from looking at your code) and I have also tried the "fight" command.  In all cases the game tells me I'm wrong then ejects me from combat mode.  

This might be a second issue, but once ejected, I cannot re-enter combat mode.

![screen shot 2017-10-18 at 1 38 42 pm](https://user-images.githubusercontent.com/13429860/31695903-b602f974-b409-11e7-8915-c844f607ff90.png)

**Comment by bluwattl** [comment]
I will make a combat tutorial, and you are going to die if you get it wrong, and the program will close.
